### ISSUE TITLE
Unable to use the repo as an NPM package.

### ISSUE THREAD

**Issue by PlaiyTiziano** [PoseiDAT/schemas#10]
Currently I can't find a way to use this repo as NPM package.

When installing this as an NPM package with the following command:
npm install git+https://github.com/PoseiDAT/schemas.git

The package will only contain the docs folder and some dotfiles (check the image below to see which files you get from installing with the above command).

![image](https://user-images.githubusercontent.com/26570835/108338478-9748c200-71d6-11eb-8cd2-837f606cc3ed.png)

Since the lib folder (which contains the built files) is in the .gitignore you'll never install them through npm as they are not present in the repo. The .npmignore file then contains the src folder which results in not being able to manually build the files either.

Thanks in advance for any further help.

**Comment by Qwerios** [comment]
I'll see about publishing a first version of the NPM package

**Comment by Qwerios** [comment]
I've done 2 things:

* published a 0.0.2 version of the package
* add npm prepare to help with git installs

Either of those should suffice for your needs. I'd recommend using the NPM package.
Please reopen this issue if you hit any issues

https://www.npmjs.com/package/@poseidat/schemas
