### ISSUE TITLE
Unable to use the schemas.

### ISSUE THREAD

**Issue by PlaiyTiziano** [PoseiDAT/schemas#11]
Currently we're unable to use the schema's that are being set for the ajv validator instance in schema-validator.ts. Because all the values in the schemas.ts file are not being exported by the main entry file of the package.

This makes the validateSchema function that is being exported not usable at the moment. Unless I'm overlooking something.

**Comment by Qwerios** [comment]
We are using the library in our own journal server and it is working as expected.
We've updated the README with some usage information.
The library provides ready to use classes that handle the data and validation for you.
Using TypeScript is highly recommended as you will get completion and type checkin g.

Please keep in mind this library is still in its infancy and the schemas are very much subject to change.

**Comment by PlaiyTiziano** [comment]
Alright, thank you for your response.
I'll close the issue then because using the provided classes will probably solve our problems.
