### ISSUE TITLE
consistency in journals

### ISSUE THREAD

**Issue by JensPauwels** [PoseiDAT/schemas#20]
Is there a reason why the parameter journal_id is not named as id in the journal object?

**Comment by Qwerios** [comment]
The convention to use named ids stems from 2 reasons:

* optimised database index and storage
* clarity for which type of id you are looking at

Adding a serial auto-incremented 'id' column to relational databases is common practice. Having the option to use an integer for a foreign key has benefits over a string/guid for index size and performance. The named id would prevent clashing with the added database id.

The clarity part comes from us humans looking at named properties. Everything can be named an `id` so seeing `journal_id` or `entry_id` seemed like a good idea.

The consistency does appear to have been lost for:

* vessel-section
* device
* equipment
* company

These should ideally be adjusted.

**Comment by JensPauwels** [comment]
Is it wise to already implement it that way or would it take too long for you to implement those changes?

**Comment by Qwerios** [comment]
The changes should be fine it's checking existing implementations and unit tests where the work is. I'll see about making a PR later this week and assign it to the required people to review

**Comment by Qwerios** [comment]
Closing this issue in favour of PR #21
