### ISSUE TITLE
New measurement type 'Illumination'

### ISSUE THREAD

**Issue by DriesVandb** [PoseiDAT/schemas#35]
The addition of the measurement type 'ILLUMINATION' is necessary to be able to support lux sensors.

"ILLUMINATION" should be added to IEnumMeasurementType.

Example:
`export declare type IEnumMeasurementType = "POSITION" | "TEMPERATURE" | "HUMIDITY" | "PRESSURE" | "SPEED" | "ONOFF" | "FORCE" | "FUEL_CONSUMPTION" | "DEPTH" | "ACCELERATION" | "MAGNETISM" | "ANGULAR_VELOCITY" | "VOLTAGE" | "CURRENT" | "POWER" | "ENERGY_CONSUMPTION" | "TRAWL_TENSION" | "SCALE" | "RPM" | "ROUTE" | "SPATIAL_AXES" | "ILLUMINATION";`

**Comment by Qwerios** [comment]
I'm closing this issue as ILLUMINATION is also in #39
