### ISSUE TITLE
Is sensor not to narrow?

### ISSUE THREAD

**Issue by daanpape** [PoseiDAT/schemas#4]
In the current schema there is a separate 'Measurement' schema and a 'NavigationPosition' schema. I woud propose not to call it sensor but device. For example, an engine can make Measurements but is not a Sensor, more a device.

In the current concentrator software we have made the following abstraction:
 - We have Devices which measure certain Quantities and saves Measurements.

In this mindset we would propose to make a NavigationPosition child of the Measurement schema. A NavigationPosition is thus a Measurement made by the Device 'GPS'.

What do you think?

**Comment by Qwerios** [comment]
Yeah that sounds very sensible. I pretty much added the sensor schemas as a placeholder to get this exact discussion going. I figured you would have way more input for those schemas then what I have at my disposal.  Feel free to remove the sensor and PR the proposed changes

**Comment by daanpape** [comment]
@Qwerios thanks for the comment. This is now clear to me, I will work on the new schema structure en make a PR asap.

**Comment by Qwerios** [comment]
@daanpape I've processed our updates from the meeting earlier today. The base structure is now documented in the README in greater detail.

When I started coding the new entry->event structure I concluded that there was too much overlap between the two. 
Also we would have to handle revisions for both entries and events which was cumbersome.
And finally if we nest events in an entry and one of the events needed to be updated we would have to resend more data then just the updated event. This would be even worse when mixing event types.

Considering the goals was to keep the journal entries small and self contained I decided to fold the events back into the entries and I think the end result makes more sense. Please review and let me know what you think. We can also setup a quick call about this is you want.

I prepared the `EquipmentInventory` entry for you with some supporting schemas that might serve as a starting point for the vessel equipment we discussed.

I'm guessing you will want to start adding the `DeviceMeasurement` entry type to replace the previous sensor placeholder (which I removed).

**Comment by Qwerios** [comment]
@daanpape just to make you aware of it I'm close to merging a sizeable PR that adds a large number of new schemas. This includes a first draft for a tow schema which only contains trip related information so far.

See: https://github.com/PoseiDAT/schemas/pull/5

**Comment by daanpape** [comment]
@Qwerios thanks for the update, I'm close to making a pull request with sensor data. I'm expecting this somewhere next week.

**Comment by Qwerios** [comment]
I will be merging my PR shortly. You may want to consider re-basing to make use of the new `entry_type` support. Also I've added support for enums which might come in handy for you.

**Comment by Qwerios** [comment]
With the merging of #8 we can close this issue
